[tool.flit.metadata]
module = "predicate"
dist-name = "py-predicate"
author = "Maurits Rijk"
author-email = "maurits.rijk@gmail.com"
home-page = "https://github.com/mrijk/py-predicate"
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
]
requires = [
    "more-itertools"
]
description-file = "README.md"
requires-python = ">=3.12"

[tool.flit.metadata.requires-extra]
test = [
    "black",
    "mypy",
    "mypy_extensions",
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "ruff",
]
dev = [
    "bumpversion",
    "jsonschema",
    "pre-commit",
]

[tool.black]
line-length = 120