"""The py-predicate module."""

__version__ = "0.0.1"

from predicate.optimizer.predicate_optimizer import can_optimize, optimize
from predicate.predicate import (
    AllPredicate,
    AlwaysFalsePredicate,
    AlwaysTruePredicate,
    AndPredicate,
    AnyPredicate,
    EqPredicate,
    FnPredicate,
    GePredicate,
    GtPredicate,
    InPredicate,
    IsEmptyPredicate,
    IsNonePredicate,
    IsNotNonePredicate,
    LePredicate,
    LtPredicate,
    NePredicate,
    NotInPredicate,
    NotPredicate,
    OrPredicate,
    Predicate,
    XorPredicate,
    always_false_p,
    always_true_p,
)
from predicate.standard_predicates import all_p, ge_p, gt_p, is_list_p, is_str_p, lazy_p, le_p, lt_p

__all__ = [
    "AllPredicate",
    "AlwaysFalsePredicate",
    "AlwaysTruePredicate",
    "AndPredicate",
    "AnyPredicate",
    "EqPredicate",
    "FnPredicate",
    "GePredicate",
    "GtPredicate",
    "InPredicate",
    "IsEmptyPredicate",
    "IsNonePredicate",
    "IsNotNonePredicate",
    "LePredicate",
    "LtPredicate",
    "NePredicate",
    "NotInPredicate",
    "NotPredicate",
    "OrPredicate",
    "Predicate",
    "XorPredicate",
    "all_p",
    "always_false_p",
    "always_true_p",
    "can_optimize",
    "ge_p",
    "gt_p",
    "is_list_p",
    "is_str_p",
    "lazy_p",
    "le_p",
    "lt_p",
    "optimize",
]
