import asyncio
from dataclasses import dataclass
from typing import Callable, Iterable, override

from predicate.is_async_predicate import is_async_p
from predicate.predicate import Predicate


def _call(fn: Callable, acc, x):
    if is_async_p(fn):
        return asyncio.run(fn(acc, x))
    return fn(acc, x)


@dataclass
class ReducePredicate[T](Predicate[T]):
    """A predicate class that models the reduce predicate."""

    fn: Callable
    initial: T

    def __call__(self, iterable: Iterable[T]) -> bool:
        acc = self.initial
        for x in iterable:
            acc, predicate = _call(self.fn, acc, x)
            if not predicate(x):
                return False
        return True

    def __repr__(self) -> str:
        name = getattr(self.fn, "__name__", str(self.fn))
        return f"reduce_p({name}, {self.initial!r})"

    @override
    def explain_failure(self, iterable: Iterable[T]) -> dict:
        acc = self.initial
        for index, x in enumerate(iterable):
            acc, predicate = _call(self.fn, acc, x)
            if not predicate(x):
                return {"index": index, "value": x} | predicate.explain_failure(x)
        return {}


def reduce_p[T](fn: Callable, initial: T) -> Predicate[T]:
    """Return True if all elements satisfy the predicate generated by fn, otherwise False."""
    return ReducePredicate(fn=fn, initial=initial)
