import asyncio
from dataclasses import dataclass, field
from itertools import accumulate, islice
from typing import Any, Callable, Iterable, override

from predicate.is_async_predicate import is_async_p
from predicate.predicate import Predicate


@dataclass
class ReducePredicate[T](Predicate[T]):
    """A predicate class that models the reduce predicate."""

    fn: Callable
    initial: T
    _call: Callable[[T, T], tuple[T, Predicate[T]]] = field(init=False, repr=False)

    def __post_init__(self):
        if is_async_p(self.fn):
            self._call = lambda acc, x: asyncio.run(self.fn(acc, x))
        else:
            self._call = self.fn

    def __call__(self, iterable: Iterable[T]) -> bool:
        initial: Any = (self.initial, None, None)
        return all(
            predicate(x)
            for _, predicate, x in islice(
                accumulate(iterable, lambda state, x: (*self._call(state[0], x), x), initial=initial),
                1,
                None,
            )
        )

    def __repr__(self) -> str:
        name = getattr(self.fn, "__name__", str(self.fn))
        return f"reduce_p({name}, {self.initial!r})"

    @override
    def explain_failure(self, iterable: Iterable[T]) -> dict:
        acc = self.initial
        for index, x in enumerate(iterable):
            acc, predicate = self._call(acc, x)
            if not predicate(x):
                return {"index": index, "value": x} | predicate.explain_failure(x)
        return {}


def reduce_p[T](fn: Callable, initial: T) -> Predicate[T]:
    """Return True if all elements satisfy the predicate generated by fn, otherwise False."""
    return ReducePredicate(fn=fn, initial=initial)
