name: Documentation

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    - id: deployment
      uses: sphinx-notes/pages@v3
